### ISSUE TITLE
Missing macros

### ISSUE THREAD

**Issue by milorambaldi** [matrix-io/matrix-malos-wakeword#10]
I get this error when doing a make on the cpp source
CMakeFiles/malos_psphinx.dir/malos_psphinx.cpp.o: In function `recognize_from_microphone()':
malos_psphinx.cpp:(.text+0xfc): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x134): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x174): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x198): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x1e4): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x230): undefined reference to `ps_get_in_speech'
malos_psphinx.cpp:(.text+0x26c): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x30c): undefined reference to `err_msg'
malos_psphinx.cpp:(.text+0x330): undefined reference to `err_msg'

**Comment by hpsaturn** [comment]
Hi, sorry for delay, please try to test the last [pull request](https://github.com/matrix-io/matrix-malos-wakeword/pull/11) or this branch `av/fix_matrixio_dependencies` please. Details in the README file on this branch. Thanks.
